### ISSUE TITLE
Release cycle and dependency tracking

### ISSUE THREAD

**Issue by yegortokmakov** [aws-solutions-library-samples/guidance-for-galaxy-on-aws#1]
To allow users track updates to this guidance and have proper versioning in their deployment pipelines, we need to define a release cycle for new versions of this repository. My suggestion is to bundle the guidance as a public NPM package. This will give users ability to lock-in specific version and more deployment flexibility.

For example, if we expose CDK in the package, users can install specific version with `npm install cdk-galaxy@v1.1.1` and do `cdk-galaxy cdk deploy`.

Another option is to import specific stack from this guidance, e.g. `import ApplicationStack from cdk-galaxy`, and use it in user managed CDK application similar to what we have in `bin/galaxy.ts`.

It would still be possible to clone the repo and use it as is, of course.

- [ ] Add Github actions to build and publish the NPM package under `cdk-galaxy`
- [ ] Lock down npm dependencies of this repo + setup dependabot
- [ ] Lock down version of the galaxy helm chart (ideally, we should find a way to get something similar to dependabot for it)
- [ ] Expose stacks in the npm package
- [ ] Update the documentation to reflect the latest changes
- [ ] Release the NPM package following semver starting with v1.0.0
